import type { DietaryFilter, MenuCategory, MenuItem, MenuSort } from "@/types/menu.types";

export const menuCategories: MenuCategory[] = ["All Dishes", "Family Packs", "Mains", "Sides", "Breakfast", "Desserts"];

export const dietaryFilters: DietaryFilter[] = ["Vegan", "GF", "Organic", "Nut-Free"];

export const menuSortOptions: { label: string; value: MenuSort }[] = [
  { label: "Most Popular", value: "popular" },
  { label: "Newest", value: "newest" },
  { label: "Highest Rated", value: "rating" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
];

export const menuItems: MenuItem[] = [
  {
    id: "harvest-quinoa",
    name: "Vegetable Quinoa Freezer Bowl",
    description: "Roasted root vegetables, kale, and maple-tahini dressing packed as a quick heat-and-serve meal.",
    price: 14.5,
    rating: 4.9,
    popularity: 98,
    createdAt: "2026-01-12",
    category: "Mains",
    tags: ["Vegan", "GF"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Harvest quinoa bowl with avocado, chickpeas, greens, and roasted vegetables.",
    },
  },
  {
    id: "wild-salmon",
    name: "Lemon Salmon Meal Pack",
    description: "Portioned salmon, rice, edamame, and citrus glaze frozen for an easy protein-rich dinner.",
    price: 18,
    rating: 4.7,
    popularity: 93,
    createdAt: "2026-02-08",
    category: "Mains",
    tags: ["Organic", "GF"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/wild-salmon-img.png",
      alt: "Wild salmon poke bowl with edamame and pickled vegetables.",
    },
  },
  {
    id: "heirloom-caprese",
    name: "Tomato Mozzarella Bake",
    description: "A comforting freezer bake with tomatoes, mozzarella, herbs, and a balsamic-style finish.",
    price: 12,
    rating: 4.8,
    popularity: 86,
    createdAt: "2025-11-18",
    category: "Sides",
    tags: ["GF", "Organic"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/heirloom-img.png",
      alt: "Heirloom tomato caprese with fresh mozzarella and basil.",
    },
  },
  {
    id: "herb-sides",
    name: "Herb Roasted Vegetable Pack",
    description: "Garden vegetables roasted with thyme and rosemary oil, frozen as a ready side.",
    price: 9,
    rating: 4.6,
    popularity: 81,
    createdAt: "2025-10-14",
    category: "Sides",
    tags: ["Vegan", "GF", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/herb-roasted-sides-img.png",
      alt: "Roasted asparagus and carrots on a ceramic plate.",
    },
  },
  {
    id: "mint-sparkler",
    name: "Mint Lemonade Concentrate",
    description: "Frozen hibiscus, mint, and citrus concentrate. Thaw, mix with water, and serve chilled.",
    price: 6.5,
    rating: 4.9,
    popularity: 91,
    createdAt: "2026-03-02",
    category: "Sides",
    tags: ["Organic", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Ruby hibiscus mint sparkler in a tall glass.",
    },
  },
  {
    id: "green-goddess",
    name: "Green Vegetable Breakfast Hash",
    description: "Greens, peas, and potatoes with a creamy herb sauce for a quick freezer breakfast.",
    price: 13,
    rating: 4.5,
    popularity: 78,
    createdAt: "2025-12-09",
    category: "Breakfast",
    tags: ["Vegan", "GF"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/green-salad-img.png",
      alt: "Green goddess salad plated on a sage ceramic dish.",
    },
  },
  {
    id: "mediterranean-grain",
    name: "Mediterranean Family Grain Tray",
    description: "Farro, chickpeas, vegetables, olives, herbs, and lemon sauce in a family-size freezer tray.",
    price: 15.5,
    rating: 4.8,
    popularity: 96,
    createdAt: "2026-04-20",
    category: "Family Packs",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Mediterranean grain bowl with chickpeas, cucumber, and fresh herbs.",
    },
  },
  {
    id: "teriyaki-chicken",
    name: "Teriyaki Chicken Freezer Bowl",
    description: "Glazed chicken, jasmine rice, edamame, and sesame vegetables portioned for fast reheating.",
    price: 17,
    rating: 4.7,
    popularity: 89,
    createdAt: "2026-01-28",
    category: "Mains",
    tags: ["GF"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/wild-salmon-img.png",
      alt: "Teriyaki chicken bowl with rice and vegetables.",
    },
  },
  {
    id: "slow-roasted-beef",
    name: "Rustic Slow-Roasted Beef Tray",
    description: "Tender slow-roasted beef with carrots, herbs, and pan jus, frozen in a family tray.",
    price: 24,
    rating: 4.9,
    popularity: 99,
    createdAt: "2025-09-22",
    category: "Family Packs",
    tags: ["GF", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/home-page/beaf-steak-img.png",
      alt: "Slow-roasted beef served with carrots and mashed potatoes.",
    },
  },
  {
    id: "lemon-herb-chicken",
    name: "Lemon Herb Chicken Tray",
    description: "Roasted chicken with lemon, garden herbs, and vegetables, cooked in batches and frozen fresh.",
    price: 21,
    rating: 4.8,
    popularity: 94,
    createdAt: "2026-05-11",
    category: "Family Packs",
    tags: ["GF", "Organic", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/beaf-steak-img.png",
      alt: "Lemon herb roasted chicken with vegetables.",
    },
  },
  {
    id: "mushroom-risotto",
    name: "Wild Mushroom Risotto Pack",
    description: "Creamy arborio rice, mushrooms, parmesan, and herbs packed for a cozy freezer dinner.",
    price: 19,
    rating: 4.7,
    popularity: 88,
    createdAt: "2026-03-26",
    category: "Mains",
    tags: ["GF", "Organic", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Creamy wild mushroom risotto finished with herbs.",
    },
  },
  {
    id: "vegetable-lasagna",
    name: "Roasted Vegetable Lasagna Tray",
    description: "Layers of roasted vegetables, tomato sauce, and dairy-free bechamel in a freezer-ready tray.",
    price: 18.5,
    rating: 4.6,
    popularity: 82,
    createdAt: "2026-02-19",
    category: "Family Packs",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/menu/heirloom-img.png",
      alt: "Roasted vegetable lasagna with tomato sauce and fresh herbs.",
    },
  },
  {
    id: "artisan-sourdough",
    name: "Freezer Sourdough Slices",
    description: "Naturally leavened bread, sliced and packed so you can toast only what you need.",
    price: 8,
    rating: 4.8,
    popularity: 90,
    createdAt: "2025-08-15",
    category: "Sides",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/bread-img.png",
      alt: "Artisan sourdough bread on a rustic surface.",
    },
  },
  {
    id: "sweet-potato-wedges",
    name: "Smoky Sweet Potato Wedges",
    description: "Oven-roasted sweet potatoes with smoked paprika and herb dip, frozen for quick sides.",
    price: 9.5,
    rating: 4.6,
    popularity: 84,
    createdAt: "2026-04-04",
    category: "Sides",
    tags: ["Vegan", "GF", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/herb-roasted-sides-img.png",
      alt: "Smoky roasted sweet potato wedges with herb dip.",
    },
  },
  {
    id: "citrus-ginger-cooler",
    name: "Citrus Ginger Freezer Cubes",
    description: "Frozen orange, lemon, and ginger cubes for quick coolers, teas, and mocktails.",
    price: 7,
    rating: 4.7,
    popularity: 80,
    createdAt: "2026-05-20",
    category: "Sides",
    tags: ["Vegan", "GF", "Organic"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Bright citrus ginger cooler served over ice.",
    },
  },
  {
    id: "berry-kombucha",
    name: "Berry Breakfast Oat Cups",
    description: "Berry and oat cups frozen in single portions for quick breakfasts or snacks.",
    price: 7.5,
    rating: 4.5,
    popularity: 75,
    createdAt: "2026-03-14",
    category: "Breakfast",
    tags: ["Vegan", "GF", "Organic"],
    tagTone: "primary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Wild berry kombucha with fresh berries and mint.",
    },
  },
  {
    id: "dark-chocolate-torte",
    name: "Frozen Dark Chocolate Torte",
    description: "Rich flourless chocolate torte portioned for the freezer and ready after a short thaw.",
    price: 10,
    rating: 4.9,
    popularity: 97,
    createdAt: "2026-02-14",
    category: "Desserts",
    tags: ["GF"],
    tagTone: "primary",
    image: {
      src: "/images/home-page/choco-strawberry-cake.png",
      alt: "Dark chocolate torte with fresh berries.",
    },
  },
  {
    id: "berry-oat-crumble",
    name: "Berry Oat Freezer Crumble",
    description: "Berries beneath a crisp cinnamon oat topping, ready to bake from frozen.",
    price: 9,
    rating: 4.6,
    popularity: 79,
    createdAt: "2026-05-30",
    category: "Desserts",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/choco-strawberry-cake.png",
      alt: "Warm berry oat crumble served in a small dish.",
    },
  },
];
