import type { DietaryFilter, MenuCategory, MenuItem, MenuSort } from "@/types/menu.types";

export const menuCategories: MenuCategory[] = ["All Dishes", "Bowls", "Mains", "Sides", "Drinks", "Desserts"];

export const dietaryFilters: DietaryFilter[] = ["Vegan", "GF", "Organic", "Nut-Free"];

export const menuSortOptions: { label: string; value: MenuSort }[] = [
  { label: "Most Popular", value: "popular" },
  { label: "Newest", value: "newest" },
  { label: "Highest Rated", value: "rating" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
];

export const menuItems: MenuItem[] = [
  {
    id: "harvest-quinoa",
    name: "Harvest Quinoa Bowl",
    description: "Roasted root vegetables, massaged kale, and maple-tahini dressing.",
    price: 14.5,
    rating: 4.9,
    popularity: 98,
    createdAt: "2026-01-12",
    category: "Bowls",
    tags: ["Vegan", "GF"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Harvest quinoa bowl with avocado, chickpeas, greens, and roasted vegetables.",
    },
  },
  {
    id: "wild-salmon",
    name: "Wild Salmon Poke",
    description: "Sustainably sourced salmon, edamame, and house citrus ponzu.",
    price: 18,
    rating: 4.7,
    popularity: 93,
    createdAt: "2026-02-08",
    category: "Bowls",
    tags: ["Organic", "GF"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/wild-salmon-img.png",
      alt: "Wild salmon poke bowl with edamame and pickled vegetables.",
    },
  },
  {
    id: "heirloom-caprese",
    name: "Heirloom Caprese",
    description: "Local farm tomatoes, buffalo mozzarella, and aged balsamic.",
    price: 12,
    rating: 4.8,
    popularity: 86,
    createdAt: "2025-11-18",
    category: "Sides",
    tags: ["GF", "Organic"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/heirloom-img.png",
      alt: "Heirloom tomato caprese with fresh mozzarella and basil.",
    },
  },
  {
    id: "herb-sides",
    name: "Herb Roasted Vegetables",
    description: "Seasonal garden vegetables roasted with thyme and rosemary oil.",
    price: 9,
    rating: 4.6,
    popularity: 81,
    createdAt: "2025-10-14",
    category: "Sides",
    tags: ["Vegan", "GF", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/herb-roasted-sides-img.png",
      alt: "Roasted asparagus and carrots on a ceramic plate.",
    },
  },
  {
    id: "mint-sparkler",
    name: "Hibiscus Mint Sparkler",
    description: "Cold-pressed hibiscus flowers, fresh mint, and sparkling spring water.",
    price: 6.5,
    rating: 4.9,
    popularity: 91,
    createdAt: "2026-03-02",
    category: "Drinks",
    tags: ["Organic", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Ruby hibiscus mint sparkler in a tall glass.",
    },
  },
  {
    id: "green-goddess",
    name: "Green Goddess Salad",
    description: "Butter lettuce, snap peas, radishes, and creamy avocado dressing.",
    price: 13,
    rating: 4.5,
    popularity: 78,
    createdAt: "2025-12-09",
    category: "Sides",
    tags: ["Vegan", "GF"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/green-salad-img.png",
      alt: "Green goddess salad plated on a sage ceramic dish.",
    },
  },
  {
    id: "mediterranean-grain",
    name: "Mediterranean Grain Bowl",
    description: "Farro, cucumber, chickpeas, olives, herbs, and lemon vinaigrette.",
    price: 15.5,
    rating: 4.8,
    popularity: 96,
    createdAt: "2026-04-20",
    category: "Bowls",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Mediterranean grain bowl with chickpeas, cucumber, and fresh herbs.",
    },
  },
  {
    id: "teriyaki-chicken",
    name: "Teriyaki Chicken Bowl",
    description: "Glazed chicken, jasmine rice, edamame, and sesame vegetables.",
    price: 17,
    rating: 4.7,
    popularity: 89,
    createdAt: "2026-01-28",
    category: "Bowls",
    tags: ["GF"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/wild-salmon-img.png",
      alt: "Teriyaki chicken bowl with rice and vegetables.",
    },
  },
  {
    id: "slow-roasted-beef",
    name: "Rustic Slow-Roasted Beef",
    description: "Tender slow-roasted beef with carrots, herbs, and pan jus.",
    price: 24,
    rating: 4.9,
    popularity: 99,
    createdAt: "2025-09-22",
    category: "Mains",
    tags: ["GF", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/home-page/beaf-steak-img.png",
      alt: "Slow-roasted beef served with carrots and mashed potatoes.",
    },
  },
  {
    id: "lemon-herb-chicken",
    name: "Lemon Herb Chicken",
    description: "Roasted chicken with lemon, garden herbs, and seasonal vegetables.",
    price: 21,
    rating: 4.8,
    popularity: 94,
    createdAt: "2026-05-11",
    category: "Mains",
    tags: ["GF", "Organic", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/beaf-steak-img.png",
      alt: "Lemon herb roasted chicken with seasonal vegetables.",
    },
  },
  {
    id: "mushroom-risotto",
    name: "Wild Mushroom Risotto",
    description: "Creamy arborio rice, woodland mushrooms, parmesan, and fresh herbs.",
    price: 19,
    rating: 4.7,
    popularity: 88,
    createdAt: "2026-03-26",
    category: "Mains",
    tags: ["GF", "Organic", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/harvest-bowl-img.png",
      alt: "Creamy wild mushroom risotto finished with herbs.",
    },
  },
  {
    id: "vegetable-lasagna",
    name: "Roasted Vegetable Lasagna",
    description: "Layers of roasted vegetables, tomato sauce, and dairy-free bechamel.",
    price: 18.5,
    rating: 4.6,
    popularity: 82,
    createdAt: "2026-02-19",
    category: "Mains",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "primary",
    image: {
      src: "/images/menu/heirloom-img.png",
      alt: "Roasted vegetable lasagna with tomato sauce and fresh herbs.",
    },
  },
  {
    id: "artisan-sourdough",
    name: "Artisan Sourdough",
    description: "Naturally leavened bread baked until crisp, golden, and airy.",
    price: 8,
    rating: 4.8,
    popularity: 90,
    createdAt: "2025-08-15",
    category: "Sides",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/bread-img.png",
      alt: "Artisan sourdough bread on a rustic surface.",
    },
  },
  {
    id: "sweet-potato-wedges",
    name: "Smoky Sweet Potato Wedges",
    description: "Oven-roasted sweet potatoes with smoked paprika and herb dip.",
    price: 9.5,
    rating: 4.6,
    popularity: 84,
    createdAt: "2026-04-04",
    category: "Sides",
    tags: ["Vegan", "GF", "Nut-Free"],
    tagTone: "tertiary",
    image: {
      src: "/images/menu/herb-roasted-sides-img.png",
      alt: "Smoky roasted sweet potato wedges with herb dip.",
    },
  },
  {
    id: "citrus-ginger-cooler",
    name: "Citrus Ginger Cooler",
    description: "Fresh orange, lemon, ginger, and sparkling mineral water.",
    price: 7,
    rating: 4.7,
    popularity: 80,
    createdAt: "2026-05-20",
    category: "Drinks",
    tags: ["Vegan", "GF", "Organic"],
    tagTone: "secondary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Bright citrus ginger cooler served over ice.",
    },
  },
  {
    id: "berry-kombucha",
    name: "Wild Berry Kombucha",
    description: "Small-batch kombucha infused with blackberry, raspberry, and mint.",
    price: 7.5,
    rating: 4.5,
    popularity: 75,
    createdAt: "2026-03-14",
    category: "Drinks",
    tags: ["Vegan", "GF", "Organic"],
    tagTone: "primary",
    image: {
      src: "/images/menu/mint-sparkler-img.png",
      alt: "Wild berry kombucha with fresh berries and mint.",
    },
  },
  {
    id: "dark-chocolate-torte",
    name: "Dark Chocolate Torte",
    description: "Rich flourless chocolate torte finished with raspberries and cream.",
    price: 10,
    rating: 4.9,
    popularity: 97,
    createdAt: "2026-02-14",
    category: "Desserts",
    tags: ["GF"],
    tagTone: "primary",
    image: {
      src: "/images/home-page/choco-strawberry-cake.png",
      alt: "Dark chocolate torte with fresh berries.",
    },
  },
  {
    id: "berry-oat-crumble",
    name: "Berry Oat Crumble",
    description: "Warm seasonal berries beneath a crisp cinnamon oat topping.",
    price: 9,
    rating: 4.6,
    popularity: 79,
    createdAt: "2026-05-30",
    category: "Desserts",
    tags: ["Vegan", "Nut-Free"],
    tagTone: "secondary",
    image: {
      src: "/images/home-page/choco-strawberry-cake.png",
      alt: "Warm berry oat crumble served in a small dish.",
    },
  },
];
